server:
  port: 8082

spring:
  application:
    name: provider-item
  redis:
    host: 192.168.1.29
    port: 6379
  session:
    store-type: redis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.29:3306/item?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
  data:
    mongodb:
      uri: mongodb://192.168.1.29:27017/tom
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl